blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='list'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),  # Подключение к URL'ам приложения catalog
    path("blog/", include("blog.urls", namespace="blog")),  # Подключение к URL'ам приложения blog
    path("users/", include("users.urls", namespace="users")),  # Подключение к URL'ам приложения users
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name="slug", **NULLABLE)
    content = models.TextField(**NULLABLE, verbose_name='Содержимое')
    image = models.ImageField(**NULLABLE, upload_to='blog/', verbose_name='Превью')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/views.py
from blog.models import Article
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify


class ArticleListView(ListView):
    model = Article

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(is_published=True)
        return queryset


class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'content', 'image',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views_count += 1
        obj.save()
        return obj


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ('title', 'content', 'image',)
    success_url = reverse_lazy('blog:list')

    def get_success_url(self):
        return reverse('blog:detail', args=[self.kwargs.get('pk')])


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blog:list')

blog/templates/blog/article_confirm_delete.html
<!doctype html>
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}

<div class="text-center">
    <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
        <form method="post">
            {% csrf_token %}
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Вы хотите удалить статью?</h4>
            </div>
            <div class="card-body">
                <button type="submit" class="btn btn-danger">Удалить</button>
                <a href="{% url 'blog:detail' object.pk %}" type="button"
                   class="btn btn-danger">Отмена</a>
            </div>
        </form>

    </div>
</div>

{% endblock %}

blog/templates/blog/article_detail.html
<!doctype html>
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}


<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.title}}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>Описание: {{object.content}}</li>
                    <li>Публикация: {{object.is_publishedr}}</li>
                    <li>Просмотров: {{object.views_count}}</li>
                    <img class="card-img-topcard-img-top" src="{{ object.image| my_media_filter }}">
                </ul>
                <a href="{% url 'blog:list' %}" type="button"
                   class="btn btn-danger">Назад</a>
                <a href="{% url 'blog:update' object.pk %}" type="button"
                   class="btn btn-secondary">Редактировать</a>
                <a href="{% url 'blog:delete' object.pk %}" type="button"
                   class="btn btn-secondary">Удалить</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}

{% block content %}


<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
            <div class="card-header">
                <h4 class="my-4 font-weight-normal">{{object.title}}</h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
                <a href="{% url 'blog:list' %}" type="button"
                   class="btn btn-danger">Назад</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/article_list.html
<!doctype html>
{% extends 'catalog/base.html' %}

{% block content %}
{% load my_tags %}
<a href="{% url 'blog:create' %}" type="button"
   class="btn btn-warning">Создать статью</a>
{% for object in object_list %}

<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.title}}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>{{object.content|truncatewords:100}}</li>
                    <li>Цена {{object.price}}</li>
                    <img class="card-img-topcard-img-top" src="{{ object.image| my_media_filter }}">
                </ul>
                <a href="{% url 'blog:detail' object.pk %}" type="button"
                   class="btn btn-danger">Посмотреть</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}