blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='list'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import ContactTemplateView, ProductDetailView, ProductListView, ProductUpdateView, ProductDeleteView, \
    ProductCreateView

from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name




urlpatterns = [
    path("", ProductListView.as_view(), name="home"),  # Главная страница
    path("contact/", ContactTemplateView.as_view(), name="contacts"),  # Страница контактов
    path("products/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product"), # Страница продукта
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"), # Страница обновления
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),  # Подключение к URL'ам приложения catalog
    path("blog/", include("blog.urls", namespace="blog")),  # Подключение к URL'ам приложения blog
    path("users/", include("users.urls", namespace="users")),  # Подключение к URL'ам приложения users
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig

from users.views import UserRegisterView, Login, Logout, RestorePassword, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('restore/', RestorePassword.as_view(), name='restore'),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),

]

catalog/models.py
from django.db import models

from blog.models import NULLABLE
from config import settings


class Category(models.Model):
    name = models.CharField(max_length=64, verbose_name="name")
    description = models.CharField(max_length=64, verbose_name="description")

    class Meta:
        verbose_name_plural = "Categories"
        verbose_name = "Categy"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=64, verbose_name="name")
    description = models.CharField(max_length=64, verbose_name="description")
    image = models.ImageField(upload_to="media/catalog", verbose_name="image")
    price = models.IntegerField(verbose_name="price")
    created_at = models.DateField(verbose_name="created", auto_now_add=True)
    update_at = models.DateField(verbose_name="updated", auto_now=True)
    manufactured_at = models.DateField(verbose_name="manufactured", auto_now_add=True)
    is_active = models.BooleanField(default=False, verbose_name="active")

    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name="category"
    )

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')


    class Meta:
        verbose_name_plural = "Products"
        verbose_name = "Product"
        permissions = [
            ('editing_is_active', 'Can edit is_active'),
            ('editing_description', 'Can edit description'),
            ('editing_category', 'Can edit category'),
        ]

    def __str__(self):
        return self.name

class ProductVersion(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version = models.PositiveIntegerField(verbose_name='Версия продукта')
    name_version = models.CharField(max_length=128, verbose_name='Название версии')
    is_active = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return f"{self.product} ({self.version})"

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from catalog.models import Product


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_active':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]

    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        if cleaned_data.lower() in ProductForm.forbidden_words:
            raise forms.ValidationError(f'Содержит запрещенное слово: {cleaned_data}. Введите другое имя продукта')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        if cleaned_data.lower() in ProductForm.forbidden_words:
            raise forms.ValidationError(f'Содержит запрещенное слово: {cleaned_data}. Введите другое описание продукта')
        return cleaned_data


class ProductVersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('is_active', 'description', 'category')

catalog/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import DetailView, ListView, TemplateView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from catalog.services import model_objects_all

from catalog.forms import ProductForm, ProductModeratorForm
from catalog.models import Product, Category, ProductVersion


# def home(request):
#     context = {
#         'object_list': Product.objects.all(),
#     }
#     return render(request, 'catalog/home.html', context)  # Отображение главной страницы


class ProductListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('users:login')
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        products = model_objects_all(Product)
        return context


# def contact(request):
#     if request.method == 'POST':
#         name = request.POST['name']
#         email = request.POST['email']
#         message = request.POST['message']
#         # Обработка данных,
#         messages.success(request, 'Ваше сообщение было отправлено успешно!')
#         return redirect('home')  # После отправки направляем на главную страницу
#     return render(request, 'catalog/contact.html')  # Отображение страницы контактов


class ContactTemplateView(TemplateView):
    template_name = "catalog/contact.html"
    extra_context = {"title": "Контакты"}


# def get_product(request, pk):
#     context = {
#         'object': Product.objects.get(pk=pk),
#     }
#     return render(request, 'catalog/product.html', context)


class ProductDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('users:login')
    model = Product


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('users:login')
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product', args=[self.object.pk])

    def get_form_class(self):
        user = self.request.user
        if (user.has_perm('catalog.editing_is_active') and
                user.has_perm('catalog.editing_description') and
                user.has_perm('catalog.editing_category')):
            return ProductModeratorForm
        elif user == self.object.owner:
            return ProductForm
        else:
            raise PermissionDenied


class ProductCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('users:login')
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        product = form.save()
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('users:login')
    model = Product
    success_url = reverse_lazy('catalog:home')

catalog/templates/catalog/includes/inc_footer.html
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    SkyStore
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                        <li><a class="text-muted" href="#">Веб-приложения</a></li>
                        <li><a class="text-muted" href="#">Микросервисы</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Мы пишем</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </footer>

catalog/templates/catalog/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
        {% if user.is_authenticated %}
        <a class="p-2" type="submit">
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="btn btn-outline-primary" type="submit">Выход</button>
            </form>
        </a>
        {% else %}
        <a href="{% url 'users:login' %}" class="p-2 text-dark">Вход</a>
        <a href="{% url 'users:register' %}" class="p-2 text-dark">Регистрация</a>
        {% endif %}

    </nav>
</div>