blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='list'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),  # Подключение к URL'ам приложения catalog
    path("blog/", include("blog.urls", namespace="blog")),  # Подключение к URL'ам приложения blog
    path("users/", include("users.urls", namespace="users")),  # Подключение к URL'ам приложения users
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig

from users.views import UserRegisterView, Login, Logout, RestorePassword, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('restore/', RestorePassword.as_view(), name='restore'),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext_lazy as _
from blog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')

    avatar = models.ImageField(upload_to='users/avatars/', **NULLABLE, verbose_name=_('avatar'))
    phone = PhoneNumberField(**NULLABLE, verbose_name=_('phone'))
    country = models.CharField(max_length=64, **NULLABLE, verbose_name=_('country'))
    token = models.CharField(max_length=64, **NULLABLE, verbose_name=_('token'))

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms
from catalog.forms import StyleFormMixin
from users.models import User


class UserRegistrationForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserAuthenticationForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User

class RestorePasswordForm(StyleFormMixin, forms.Form):
    email = forms.EmailField()

users/views.py
from django.views.generic import CreateView, FormView
from django.contrib.auth.views import LoginView, LogoutView
from users.models import User
from users.forms import UserRegistrationForm, UserAuthenticationForm, RestorePasswordForm
from django.urls import reverse_lazy, reverse
from config import settings
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.hashers import make_password
import random
import secrets

class UserRegisterView(CreateView):
    model = User
    form_class = UserRegistrationForm
    success_url = reverse_lazy('catalog:home')
    template_name = 'users/register.html'

    def form_valid(self, form):
        new_user = form.save()
        new_user.is_active = False
        token = secrets.token_hex(16)
        new_user.token = token
        new_user.save()

        host = self.request.get_host()
        url = f'http://{host}/users/email_confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Перейдите по ссылки для подтверждения почты {url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email],
        )

        return super().form_valid(form)


class Login(LoginView):
    template_name = 'users/login.html'
    form_class = UserAuthenticationForm
    success_url = reverse_lazy('catalog:home')


class Logout(LogoutView):
    pass


class RestorePassword(FormView):
    form_class = RestorePasswordForm
    template_name = 'users/restore_password.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            email = form.cleaned_data.get('email')
            user = get_object_or_404(User, email=email)
            new_password = ''.join(str(random.randint(0, 9)) for _ in range(12))
            user.password = make_password(new_password)
            send_mail(
                subject='Вы сменили пароль',
                message=f'Ваш новый пароль {new_password}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
            user.save()

        return super().form_valid(form)


def email_verification(response, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    send_mail(
        subject='Поздравляем с регистрацией',
        message='Вы зарегистрировались на нашей платформе. Добро пожаловать!',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[user.email],
    )
    return redirect(reverse('users:login'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="text-center">
    <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
        <form method="post">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Авторизация</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Войти</button>
            </div>
        </form>
        <div class="card-footer">
            <a href="{% url 'users:restore' %}" class="btn btn-danger">Восстановить пароль</a>
        </div>

    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="text-center">
    <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
        <form method="post">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Регистрация</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Зарегестрироваться</button>
            </div>
        </form>

    </div>
</div>
{% endblock %}

users/templates/users/restore_password.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="text-center">
    <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
        <form method="post">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Восстановить пароль</h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Отправить</button>
            </div>
        </form>

    </div>
</div>
{% endblock %}