blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', ArticleListView.as_view(), name='list'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import ContactTemplateView, ProductDetailView, ProductListView, ProductUpdateView, ProductDeleteView, \
    ProductCreateView

from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name




urlpatterns = [
    path("", ProductListView.as_view(), name="home"),  # Главная страница
    path("contact/", ContactTemplateView.as_view(), name="contacts"),  # Страница контактов
    path("products/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product"), # Страница продукта
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"), # Страница обновления
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),  # Подключение к URL'ам приложения catalog
    path("blog/", include("blog.urls", namespace="blog")),  # Подключение к URL'ам приложения blog
    path("users/", include("users.urls", namespace="users")),  # Подключение к URL'ам приложения users
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from blog.models import NULLABLE
from config import settings


class Category(models.Model):
    name = models.CharField(max_length=64, verbose_name="name")
    description = models.CharField(max_length=64, verbose_name="description")

    class Meta:
        verbose_name_plural = "Categories"
        verbose_name = "Categy"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=64, verbose_name="name")
    description = models.CharField(max_length=64, verbose_name="description")
    image = models.ImageField(upload_to="media/catalog", verbose_name="image")
    price = models.IntegerField(verbose_name="price")
    created_at = models.DateField(verbose_name="created", auto_now_add=True)
    update_at = models.DateField(verbose_name="updated", auto_now=True)
    manufactured_at = models.DateField(verbose_name="manufactured", auto_now_add=True)
    is_active = models.BooleanField(default=False, verbose_name="active")

    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name="category"
    )

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')


    class Meta:
        verbose_name_plural = "Products"
        verbose_name = "Product"
        permissions = [
            ('editing_is_active', 'Can edit is_active'),
            ('editing_description', 'Can edit description'),
            ('editing_category', 'Can edit category'),
        ]

    def __str__(self):
        return self.name

class ProductVersion(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version = models.PositiveIntegerField(verbose_name='Версия продукта')
    name_version = models.CharField(max_length=128, verbose_name='Название версии')
    is_active = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return f"{self.product} ({self.version})"

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from catalog.models import Product


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_active':
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]

    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        if cleaned_data.lower() in ProductForm.forbidden_words:
            raise forms.ValidationError(f'Содержит запрещенное слово: {cleaned_data}. Введите другое имя продукта')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        if cleaned_data.lower() in ProductForm.forbidden_words:
            raise forms.ValidationError(f'Содержит запрещенное слово: {cleaned_data}. Введите другое описание продукта')
        return cleaned_data


class ProductVersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('is_active', 'description', 'category')

catalog/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.views.generic import DetailView, ListView, TemplateView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from catalog.services import model_objects_all

from catalog.forms import ProductForm, ProductModeratorForm
from catalog.models import Product, Category, ProductVersion


# def home(request):
#     context = {
#         'object_list': Product.objects.all(),
#     }
#     return render(request, 'catalog/home.html', context)  # Отображение главной страницы


class ProductListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('users:login')
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        products = model_objects_all(Product)
        return context


# def contact(request):
#     if request.method == 'POST':
#         name = request.POST['name']
#         email = request.POST['email']
#         message = request.POST['message']
#         # Обработка данных,
#         messages.success(request, 'Ваше сообщение было отправлено успешно!')
#         return redirect('home')  # После отправки направляем на главную страницу
#     return render(request, 'catalog/contact.html')  # Отображение страницы контактов


class ContactTemplateView(TemplateView):
    template_name = "catalog/contact.html"
    extra_context = {"title": "Контакты"}


# def get_product(request, pk):
#     context = {
#         'object': Product.objects.get(pk=pk),
#     }
#     return render(request, 'catalog/product.html', context)


class ProductDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('users:login')
    model = Product


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('users:login')
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product', args=[self.object.pk])

    def get_form_class(self):
        user = self.request.user
        if (user.has_perm('catalog.editing_is_active') and
                user.has_perm('catalog.editing_description') and
                user.has_perm('catalog.editing_category')):
            return ProductModeratorForm
        elif user == self.object.owner:
            return ProductForm
        else:
            raise PermissionDenied


class ProductCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('users:login')
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        product = form.save()
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('users:login')
    model = Product
    success_url = reverse_lazy('catalog:home')

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="container">
    <div class="row text-center">
        {% block content %}
        {% endblock %}
        {% include 'catalog/includes/inc_footer.html' %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/contact.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}

<div class="text-center">
    <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
        <form method="post">
            {% csrf_token %}
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Вы хотите удалить продукт?</h4>
            </div>
            <div class="card-body">
                <button type="submit" class="btn btn-danger">Удалить</button>
                <a href="{% url 'catalog:product' object.pk %}" type="button"
                   class="btn btn-danger">Отмена</a>
            </div>
        </form>

    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
<!doctype html>
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>{{object.description|truncatewords:100}}</li>
                    <li>Цена {{object.price}}</li>
                    <img class="card-img-top" src="{{ object.image| my_media_filter }}">
                </ul>
                <a href="{% url 'catalog:home' %}" type="button"
                   class="btn btn-danger">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}


<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
            <div class="card-header">
                <h4 class="my-4 font-weight-normal">{{object.title}}</h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
                <a href="{% url 'catalog:home' %}" type="button"
                   class="btn btn-danger">Назад</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
<!doctype html>
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<a href="{% url 'catalog:product_create' %}" type="button"
   class="btn btn-warning">Создать Продукт</a>
{% for object in object_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card text-bg-primary mb-0" style="max-width: 20rem;">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>{{object.description|truncatewords:100}}</li>
                    <li>Цена {{object.price}}</li>
                    <li>Версия продукта {{object.productversion_set.version}}</li>
                    <img class="card-img-top" src="{{ object.image| my_media_filter }}">
                </ul>
                <a href="{% url 'catalog:product' object.pk %}" type="button"
                   class="btn btn-danger">Купить</a>
                {% if perms.catalog.editing_is_active and perms.catalog.editing_description and perms.catalog.editing_category or user == object.owner%}
                <a href="{% url 'catalog:product_update' object.pk %}" type="button"
                   class="btn btn-secondary">Редактировать</a>
                {% endif %}
                <a href="{% url 'catalog:product_delete' object.pk %}" type="button"
                   class="btn btn-secondary">Удалить</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}